In [3]:
import numpy as np
import matplotlib.pyplot as plt
import sympy as sym
from scipy import integrate
import pandas as pd
from matplotlib import rc
import os.path as path
import os


Álgebra Lineal

3.

In [2]:
def Multiplica(m_1, m_2):
    resp=np.dot(m_1,m_2)
    
    return resp

In [5]:
a=np.array([[1,0,0],[5,1,0],[-2,3,1]])
b=np.array([[4,-2,1],[0,3,7],[0,0,2]])

a,b

(array([[ 1,  0,  0],
        [ 5,  1,  0],
        [-2,  3,  1]]),
 array([[ 4, -2,  1],
        [ 0,  3,  7],
        [ 0,  0,  2]]))

In [6]:
Multiplica(a,b)

array([[ 4, -2,  1],
       [20, -7, 12],
       [-8, 13, 21]])

4.

5.

6.

7.

In [4]:
A=np.array([[4,-2,1],[20,-7,12],[-8,13,17]])
A

array([[ 4, -2,  1],
       [20, -7, 12],
       [-8, 13, 17]])

In [28]:
n = len(A)
L = np.eye(n)
U = np.copy(A)
L

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
for j in range(n-1):
    for i in range(j+1, n):
        valor = U[i, j] / U[j, j]
        L[i, j] = valor
        U[i, j:] = U[i, j:] - valor * U[j, j:]

In [30]:
L,U

(array([[ 1.,  0.,  0.],
        [ 5.,  1.,  0.],
        [-2.,  3.,  1.]]),
 array([[ 4, -2,  1],
        [ 0,  3,  7],
        [ 0,  0, -2]]))

9.

a)

In [23]:
A=np.array([[4,1,1],[1,3,2],[1,2,5]])
b=np.array([1.,3.,7.])

In [24]:
def Jacobi(A,b,x0, itmax=1000, tolerancia= 1e-9):
    
    x = x0.copy()
    
    for it in range(itmax):
        
        xn = np.zeros_like(x0)
        
        for i in range(A.shape[0]):
            
            sum_ = 0.
            
            for j in range(A.shape[1]):
                
                if j!=i:
                    sum_ += A[i,j]*x[j]
                    
            xn[i] = (b[i] - sum_)/A[i,i]
            
        print(it,xn)
        
        residuo = np.linalg.norm( np.dot(A,xn) - b )
        x = xn.copy()
        #print(residuo)
        
        if np.allclose(residuo,tolerancia,atol=tolerancia):
            break
        
    return x


In [22]:
x0 = np.array([0.,0.,0.])
Jacobi(A,b,x0)

0 [0.25       0.33333333 0.2       ]
1 [0.11666667 0.11666667 0.01666667]
2 [0.21666667 0.28333333 0.13      ]
3 [0.14666667 0.17444444 0.04333333]
4 [0.19555556 0.25555556 0.10088889]
5 [0.16088889 0.20088889 0.05866667]
6 [0.18511111 0.24059259 0.08746667]
7 [0.16798519 0.21331852 0.06674074]
8 [0.17998519 0.23284444 0.08107556]
9 [0.17152    0.2192879  0.07086519]
10 [0.17746173 0.22891654 0.07798084]
11 [0.17327565 0.2221922  0.07294104]
12 [0.17621669 0.22694742 0.07646799]
13 [0.17414615 0.22361578 0.07397769]
14 [0.17560163 0.22596616 0.07572446]
15 [0.17457735 0.22431648 0.07449321]
16 [0.17529758 0.22547874 0.07535794]
17 [0.17479083 0.22466218 0.07474899]
18 [0.17514721 0.22523707 0.07517696]
19 [0.17489649 0.22483296 0.07487573]
20 [0.17507283 0.22511735 0.07508752]
21 [0.17494878 0.22491738 0.0749385 ]
22 [0.17503603 0.22505808 0.07504329]
23 [0.17497466 0.22495913 0.07496956]
24 [0.17501783 0.22502874 0.07502142]
25 [0.17498746 0.22497978 0.07498494]
26 [0.17500882 0.22501

array([0.175, 0.225, 0.075])

b)

In [25]:
resp=np.linalg.eig(A)
resp

(array([6.89510652, 3.39729507, 1.70759841]),
 array([[ 0.43170413,  0.88573564,  0.17059871],
        [ 0.49725362, -0.07589338, -0.86427949],
        [ 0.75257583, -0.45794385,  0.47319874]]))

10.

In [54]:
A = np.array([[1, 2, -1], [1,0, -1], [4, -4, 5]])
x0 = np.array([1, 1, 1])

A

array([[ 1,  2, -1],
       [ 1,  0, -1],
       [ 4, -4,  5]])

12.

13.

14.

15. 

Mínimos Cuadrados

1.

3. 

6.

7.